DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       USERNAME VARCHAR(255) NOT NULL,
                       PASSWORD VARCHAR(255) NOT NULL,
                       ROLE VARCHAR(50) NOT NULL,
                       ENABLED BOOLEAN NOT NULL,
                       EMAIL VARCHAR(255)
);
